// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

//  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
 
  TutorialSidebar: [
    {
    type: "doc",
    id : 'intro', // Reference to a document
    // 'intro.md',
    },
    {
      type: 'html',
      value: 'Getting Started', // This is the non-clickable header
      className: 'sidebar-header', // Optional: add a custom class for styling
    },
    // {
    //   type: "doc",
    //   id : 'getting-started/overview', // Reference to a document
    //   },
      {
        type: "doc",
        id : 'getting-started/core-concept', // Reference to a document
        },
    {
      type: "doc",
      id : 'getting-started/account-setup', // Reference to a document
      },
    {
      type: "doc",
      id : 'getting-started/navigating-index', // Reference to a document
      },
    {
      type: 'category',
      label: 'Quick Start Guide',
      items: [
        'getting-started/quick-start-guide/data-query',
        'getting-started/quick-start-guide/data-visualization',
  
      ],
    },

    {
      type: 'html',
      value: 'Index Integrations', // This is the non-clickable header
      className: 'sidebar-header', // Optional: add a custom class for styling
    },
    {
      type: 'category',
      label: 'Supported Data Source',
      items: [
        'index-integration/supported-data-source/bigquery',
        'index-integration/supported-data-source/mysql',
        'index-integration/supported-data-source/postgres',
      ],
    },
    {
      type: "doc",
      id : 'index-integration/connecting-to-a-datasource', // Reference to a document
      },
    {
      type: "doc",
      id : 'index-integration/managing-data-connection', // Reference to a document
      },
    {
      type: 'html',
      value: 'User Guide', // This is the non-clickable header
      className: 'sidebar-header', // Optional: add a custom class for styling
    },
    {
      type: "doc",
      id : 'user-guide/data-exploration', // Reference to a document
      },
    {
      type: "doc",
      id : 'user-guide/building-dashboard', // Reference to a document
      },
    {
      type: "doc",
      id : 'user-guide/collaboration-features', // Reference to a document
      },
    {
      type: "doc",
      id : 'user-guide/visualization-tools', // Reference to a document
      },
    {
      type: 'html',
      value: 'Community', // This is the non-clickable header
      className: 'sidebar-header', // Optional: add a custom class for styling
    },

    {
      type: "doc",
      id : 'community/code-of-conduct', // Reference to a document
      },
    {
      type: "link",
      label: "Slack",
      href: "https://join.slack.com/t/index-community/shared_invite/zt-23cfob3ea-rMJrTNs~oqGUxiD9u2cGKA",
    },

    {
      type: 'html',
      value: 'Product Updates', // This is the non-clickable header
      className: 'sidebar-header', // Optional: add a custom class for styling
    },
    {
      type: "link",
      label: "Announcements",
      href: "https://index.app/blog/?category=announcements&page=1",
    },
    {
      type: 'category',
      label: 'Changelog',
      link: {
        type: "generated-index",
        description: "Detailed information on new features and improvements."

      },
      items: [
        'changelog/v-0.1.47',
        'changelog/v-0.1.46',
      ],
    },
  ],
};

export default sidebars;
